# ClemenTime Scheduler Configuration
# Example configuration file showing CSV usage and environment variable support

course:
  name: "Statistics 101"
  term: "Fall 2024"
  total_students: 150
  instructor: "Professor Smith"

# Organization settings (optional)
organization:
  domain: "university.edu"  # Your organization's email domain
  timezone: "America/Los_Angeles"  # Timezone for calendar events

# Terminology configuration (optional)
# Customize labels used throughout the application
terminology:
  facilitator_label: "TA"           # Default: "Facilitator" (options: "TA", "Instructor", "Coach", etc.)
  participant_label: "Student"     # Default: "Participant" (options: "Student", "Client", "Patient", etc.)

scheduling:
  exam_duration_minutes: 15
  buffer_minutes: 5
  start_time: "09:00"
  end_time: "17:00"
  excluded_days:
    - Saturday
    - Sunday
  schedule_frequency_weeks: 2
  break_duration_minutes: 5

sections:
  # Example using CSV file for students (recommended for large classes)
  - id: "section_01"
    ta_name: "John Doe"
    ta_email: "john.doe@university.edu"
    # ta_slack_id and google_email can be set here or via FACILITATOR_MAPPING env
    location: "Room 101, Building A"
    preferred_days:
      - Monday
      - Wednesday
    students_csv: "data/students/section_01.csv"  # CSV with columns: name, email, slack_id
    # Optional: Split students across multiple weeks for oral exams
    student_split:
      enabled: true  # Enable student splitting
      split_percentage: 50  # 50% of students in first week, 50% in second week
      weeks_between_splits: 2  # 2 weeks between splits (week 1&2, then week 3&4, etc.)

  # Example using inline students (good for small sections)
  - id: "section_02"
    ta_name: "Jane Smith"
    ta_email: "jane.smith@university.edu"
    location: "Room 202, Building B"
    preferred_days:
      - Tuesday
      - Thursday
    students:
      - name: "Student Name 1"
        email: "student1@university.edu"
        slack_id: "U99999999"
      - name: "Student Name 2"
        email: "student2@university.edu"
        slack_id: "U88888888"
    # Optional: Different split configuration (60/40 split with 1 week between)
    student_split:
      enabled: true
      split_percentage: 60  # 60% in first week, 40% in second week
      weeks_between_splits: 1  # 1 week between splits (week 1, then week 2, etc.)

google_meet:
  calendar_invites_enabled: false  # Whether to create calendar invites with meeting links (default: false)
  recording_settings:
    auto_recording: true
    save_to_drive: true

# AI Recording Service Configuration (optional)
# Automatically invite AI note-taking services to meetings
ai_recording:
  enabled: false
  service_email: "fred@fireflies.ai"  # Or "zoom@otter.ai", "recording@grain.com"
  service_name: "Fireflies.ai"  # Or "Otter.ai", "Grain"
  auto_invite: true  # Automatically add to calendar invites
  notification_enabled: true  # Notify when AI bot joins/leaves

notifications:
  reminder_days_before: [7, 3, 1]
  reminder_time: "09:00"
  include_meet_link: true
  include_location: true
  ta_summary_enabled: true
  ta_summary_time: "08:00"
  student_notification_title: "Session for {name}" # Customizable title template

# Slack IDs of teaching team admins who receive TA channel notifications
admin_users:
  - "U12345678"  # Professor Slack ID
  - "U87654321"  # Head TA Slack ID

# Week-by-week Google Form links for grade submission (optional)
weekly_forms:
  - week: 1
    google_form_url: "https://forms.gle/your-week1-form-id"
    description: "Week 1 Grade Submission"
  - week: 2
    google_form_url: "https://forms.gle/your-week2-form-id"
    description: "Week 2 Grade Submission"
  # Add more weeks as needed

# Recording configuration for TA sessions (optional)
recording:
  base_url: "https://stanford.zoom.us/rec/" # Base recording URL
  ta_specific: true # Each TA gets unique recording links

# Web UI Configuration (optional)
# Customize the web interface appearance and branding
web_ui:
  navbar_title: "Session Scheduler" # Custom title for the navbar
  server_base_url: "http://localhost:3000" # Base URL for the web server (change for deployment)

# Slack Channel Configuration (optional)
# Configure prefixes and suffixes for TA channel names
slack_channels:
  prefix: "course101"     # Will create channels like: "course101-ta-john-doe"
  suffix: "fall2024"      # Will create channels like: "ta-john-doe-fall2024"

# Test Mode Configuration (optional)
# Redirects all Slack notifications to a single user for testing
test_mode:
  enabled: false
  redirect_to_slack_id: "U12345678"  # Your Slack ID for test messages
  fake_student_prefix: "Test Student"
  number_of_fake_students: 30
  test_email: "test@university.edu" # Email for testing calendar invites

# Dashboard Authentication (required for production)
# Google email addresses authorized to access the web dashboard
# Users can also be managed via the web interface at /admin/users
authorized_google_users:
  - "professor@university.edu"
  - "head-ta@university.edu"
  - "ta1@university.edu"
  - "ta2@university.edu"

# =============================================================================
# Environment Variables Reference
# =============================================================================
# See .env.example for detailed configuration instructions
#
# Required environment variables:
#   - GOOGLE_CLIENT_ID (Dashboard auth + Meet/Calendar API)
#   - GOOGLE_CLIENT_SECRET (Dashboard auth + Meet/Calendar API)
#   - GOOGLE_MEET_REFRESH_TOKEN (Get by running: npm run auth)
#   - SESSION_SECRET (Random string for session encryption)
#   - SLACK_BOT_TOKEN (Slack bot OAuth token)
#   - SLACK_APP_TOKEN (Slack app-level token for Socket Mode)
#   - SLACK_SIGNING_SECRET (Slack webhook verification)
#
# Optional environment variables:
#   - FACILITATOR_MAPPING (JSON mapping of TAs to Slack/Google IDs)
#   - PORT (Web server port, default: 3000)
#   - NODE_ENV (development or production)
#   - DB_PATH (SQLite database location, default: data/clementime.db)
