services:
  clementime:
    build:
      context: .
      tags:
        - clementime:latest
    image: clementime:latest
    container_name: clementime-scheduler
    command: ["npx", "tsx", "src/index.ts", "web"]
    ports:
      - "${PORT:-4001}:3000"
    volumes:
      - ${CONFIG_PATH:-./config.yml}:/app/config.yml:ro
      - ${DATA_PATH:-./data}:/app/data
      - ${LOGS_PATH:-./logs}:/app/logs
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3000
      - CONFIG_PATH=/app/config.yml

      # Google Service Account (required)
      - GOOGLE_SERVICE_ACCOUNT_KEY=${GOOGLE_SERVICE_ACCOUNT_KEY}

      # Google OAuth (fallback)
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}

      # Google Drive
      - GOOGLE_DRIVE_SHARED_FOLDER_ID=${GOOGLE_DRIVE_SHARED_FOLDER_ID}
      - GOOGLE_DRIVE_RECORDINGS_FOLDER=${GOOGLE_DRIVE_RECORDINGS_FOLDER}

      # Slack
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
