# SwiftLint Configuration
# https://github.com/realm/SwiftLint

# Paths to include during linting
included:
  - Clementime

# Paths to exclude from linting
excluded:
  - Clementime.xcodeproj
  - Clementime.xcworkspace
  - .build
  - build
  - DerivedData

# Enabled rules
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo
  - trailing_whitespace
  - force_unwrapping
  - line_length
  - file_length
  - function_body_length
  - type_body_length
  - cyclomatic_complexity
  - function_parameter_count
  - large_tuple
  - identifier_name
  - prefer_explicit_type_over_literal
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - trailing_closure
  - implicit_optional_initialization
  - for_where
  - unused_enumerated
  - unused_closure_parameter
  - closure_end_indentation
  - sorted_first_last
  - contains_over_filter_is_empty

# Rule customization
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

# Force unwrapping should be avoided
force_unwrapping: error

# Force cast should be avoided
force_cast: warning

# Implicitly unwrapped optionals should be avoided
implicitly_unwrapped_optional:
  severity: warning
  mode: all_except_iboutlets

# Custom rules
custom_rules:
  # Prefer using Array and Dictionary over [] and [:]
  prefer_explicit_type_over_literal:
    name: "Prefer explicit type over literal"
    regex: '= \[\]'
    message: "Prefer explicit type initialization over literal []"
    severity: warning
