#!/bin/bash

# Script to generate BuildInfo.swift with git commit hash
# This should be run as a build phase in Xcode

# Get the git commit hash (short version)
GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

# Path to the generated file
OUTPUT_FILE="${SRCROOT}/Core/BuildInfo.swift"

# Generate the Swift file
cat > "$OUTPUT_FILE" << EOF
//
//  BuildInfo.swift
//  Clementime
//
//  Auto-generated by build script - Do not edit manually
//  Generated on: $(date)
//

struct BuildInfo {
    static let gitCommitHash = "$GIT_COMMIT"
}
EOF

echo "Generated BuildInfo.swift with commit: $GIT_COMMIT"
